import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gill = localFont({
  src: "../../public/gill.otf",
  variable: "--font-gill",
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${gill.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
